// ─── National College Data (College Scorecard) ───────────────────
//
// Imports the merged colleges.json generated by scripts/build-college-data.mjs
// from the College Scorecard dataset (Most-Recent-Cohorts-Institution.csv).
// 2,667 degree-granting institutions across 50 states + territories.

import type { College } from "@/types";
import collegesJson from "@/data/colleges/colleges.json";

// The JSON is typed as a plain array; cast to College[] since the ETL
// generates objects that match the interface.
export const allColleges = collegesJson as unknown as College[];

// Fast lookups
export const collegeMap = new Map<string, College>(
  allColleges.map((c) => [c.id, c])
);

// State-level grouping
export const collegesByState = allColleges.reduce<
  Record<string, College[]>
>((acc, c) => {
  const state = c.state || "ZZ";
  if (!acc[state]) acc[state] = [];
  acc[state].push(c);
  return acc;
}, {});

// Statistics
export const nationalStats = {
  totalColleges: allColleges.length,
  publicColleges: allColleges.filter((c) => c.type === "public").length,
  privateColleges: allColleges.filter((c) => c.type === "private").length,
  forProfitColleges: allColleges.filter((c) => c.type === "for-profit").length,
  uniqueStates: Object.keys(collegesByState).filter((s) => s.length === 2).length,
};
