import type { Grant, Loan, Scholarship } from "@/types";

export const grants: Grant[] = [
  {
    id: "pell-grant",
    name: "Federal Pell Grant",
    source: "federal",
    description:
      "The Pell Grant is the largest federal grant program for undergraduates. Awarded based on financial need as determined by the FAFSA. Does not need to be repaid.",
    maxAmount: 7395,
    eligibility: [
      "Undergraduate students only",
      "Must demonstrate financial need via FAFSA",
      "U.S. citizen or eligible non-citizen",
      "Enrolled in participating institution",
    ],
    applicationRequired: true,
    deadline: "June 30 (following academic year)",
    website: "https://studentaid.gov/understand-aid/types/grants/pell",
    renewable: true,
  },
  {
    id: "fseog",
    name: "Federal Supplemental Educational Opportunity Grant (FSEOG)",
    source: "federal",
    description:
      "Campus-based grant for undergraduates with exceptional financial need. Priority given to Pell Grant recipients. Funds are limited and awarded by participating schools.",
    maxAmount: 4000,
    eligibility: [
      "Undergraduate students with exceptional need",
      "Must be Pell Grant eligible",
      "Enrolled at participating institution",
    ],
    applicationRequired: true,
    deadline: "Varies by institution",
    website: "https://studentaid.gov/understand-aid/types/grants/fseog",
    renewable: true,
  },
  {
    id: "teach-grant",
    name: "TEACH Grant",
    source: "federal",
    description:
      "Provides grants to students who agree to teach in a high-need field at a low-income school. Requires a service obligation — converts to a loan if not fulfilled.",
    maxAmount: 4000,
    eligibility: [
      "Enrolled in TEACH-Grant-eligible program",
      "Score above 75th percentile on admissions test or maintain 3.25+ GPA",
      "Sign Agreement to Serve",
      "Teach in high-need field at low-income school for 4 years",
    ],
    applicationRequired: true,
    deadline: "Varies by institution",
    website: "https://studentaid.gov/understand-aid/types/grants/teach",
    renewable: true,
  },
  {
    id: "iraq-afghan-grant",
    name: "Iraq and Afghanistan Service Grant",
    source: "federal",
    description:
      "For students whose parent or guardian died as a result of military service in Iraq or Afghanistan after 9/11. Must be ineligible for Pell Grant based on EFC.",
    maxAmount: 7395,
    eligibility: [
      "Parent/guardian died due to military service in Iraq or Afghanistan",
      "Under 24 years old or enrolled in college at time of parent's death",
      "Not eligible for Pell Grant",
    ],
    applicationRequired: true,
    deadline: "June 30 (following academic year)",
    website: "https://studentaid.gov/understand-aid/types/grants/iraq-afghanistan-service",
    renewable: true,
  },
  {
    id: "texas-tuition-equalization",
    name: "Texas Tuition Equalization Grant (TEG)",
    source: "state",
    description:
      "Need-based grant for Texas residents attending private, non-profit colleges in Texas. Helps equalize tuition between public and private institutions.",
    maxAmount: 3800,
    eligibility: [
      "Texas resident",
      "Enrolled at eligible Texas private non-profit institution",
      "Demonstrate financial need via FAFSA or TASFA",
      "Enrolled at least half-time",
      "Not receiving athletic scholarship",
    ],
    applicationRequired: true,
    deadline: "Varies by institution (typically March-April)",
    website: "https://www.highered.texas.gov/grants-loans/",
    renewable: true,
  },
  {
    id: "texas-pell-completion",
    name: "Texas Pell Grant Completion Bonus",
    source: "state",
    description:
      "One-time grant for Texas Pell Grant recipients who complete their associate or bachelor's degree within a specific timeframe.",
    maxAmount: 2000,
    eligibility: [
      "Texas resident",
      "Received Pell Grant in prior year",
      "Complete associate degree within 3 years or bachelor's within 5 years",
    ],
    applicationRequired: false,
    deadline: "Automatic",
    website: "https://www.highered.texas.gov/grants-loans/",
    renewable: false,
  },
  {
    id: "texas-exemption-hazlewood",
    name: "Hazlewood Act Exemption",
    source: "state",
    description:
      "Texas property tax exemption for veterans. Provides up to 150 credit hours of tuition and fee exemption at Texas public colleges.",
    maxAmount: 25000,
    eligibility: [
      "Texas resident at time of military entry",
      "Honorable discharge or still serving",
      "Served at least 181 days active duty",
      "Enrolled at Texas public institution",
    ],
    applicationRequired: true,
    deadline: "Varies by institution",
    website: "https://www.tvc.texas.gov/education/hazlewood/",
    renewable: true,
  },
];

export const loans: Loan[] = [
  {
    id: "direct-subsidized",
    name: "Federal Direct Subsidized Loan",
    type: "federal-subsidized",
    description:
      "Need-based loan where the government pays the interest while you're in school at least half-time, during grace periods, and during deferment.",
    interestRate: "5.50%",
    originationFee: "1.057%",
    maxAmount: 5500,
    eligibility: [
      "Undergraduate students with financial need",
      "Must file FAFSA",
      "Enrolled at least half-time",
      "U.S. citizen or eligible non-citizen",
    ],
    repaymentInfo:
      "6-month grace period after graduation. Standard repayment is 10 years. Income-driven repayment plans available.",
    subsidized: true,
  },
  {
    id: "direct-unsubsidized",
    name: "Federal Direct Unsubsidized Loan",
    type: "federal-unsubsidized",
    description:
      "Loan for undergraduate and graduate students that is NOT need-based. Interest accrues from the time the loan is disbursed.",
    interestRate: "5.50% (undergrad)",
    originationFee: "1.057%",
    maxAmount: 20500,
    eligibility: [
      "Undergraduate or graduate students",
      "Must file FAFSA",
      "Enrolled at least half-time",
      "U.S. citizen or eligible non-citizen",
    ],
    repaymentInfo:
      "6-month grace period after graduation. Standard repayment is 10 years. Can postpone payments through deferment.",
    subsidized: false,
  },
  {
    id: "direct-plus-parent",
    name: "Federal Direct PLUS Loan (Parent)",
    type: "federal-plus",
    description:
      "Loans for parents of dependent undergraduate students to help cover education costs not covered by other financial aid. Credit check required.",
    interestRate: "7.54%",
    originationFee: "4.228%",
    maxAmount: 999999,
    eligibility: [
      "Parent of dependent undergraduate student",
      "Must file FAFSA",
      "No adverse credit history",
      "U.S. citizen or eligible non-citizen",
    ],
    repaymentInfo:
      "Repayment begins 60 days after full disbursement. Can defer while student is enrolled at least half-time.",
    subsidized: false,
  },
  {
    id: "direct-plus-grad",
    name: "Federal Direct PLUS Loan (Graduate)",
    type: "federal-plus",
    description:
      "Loans for graduate and professional students to help cover costs not covered by other financial aid. Credit check required.",
    interestRate: "7.54%",
    originationFee: "4.228%",
    maxAmount: 999999,
    eligibility: [
      "Graduate or professional student",
      "Must file FAFSA",
      "No adverse credit history",
      "U.S. citizen or eligible non-citizen",
    ],
    repaymentInfo:
      "6-month grace period after graduation. Standard repayment is 10 years.",
    subsidized: false,
  },
  {
    id: "texas-b-on-time",
    name: "Texas B-On-Time Loan",
    type: "private",
    description:
      "State-sponsored no-interest loan for Texas students who complete a rigorous high school curriculum and meet college readiness standards. Can be fully forgiven.",
    interestRate: "0%",
    originationFee: "0%",
    maxAmount: 5000,
    eligibility: [
      "Texas resident",
      "Completed Texas high school",
      "Completed recommended or advanced curriculum",
      "Demonstrate financial need",
    ],
    repaymentInfo:
      "Loan is forgiven at graduation if student completes degree within 4 years with 3.0+ GPA and worked 20+ hours/week for 2 years.",
    subsidized: true,
  },
];

export const scholarships: Scholarship[] = [
  {
    id: "texas-exemptions",
    name: "Texas Public Education Grant (TPEG)",
    type: "need-based",
    provider: "Texas Higher Education Coordinating Board",
    description:
      "Need-based scholarship from tuition set-aside funds at each Texas public college. Award amounts vary by institution.",
    amount: 3000,
    eligibility: [
      "Texas resident",
      "Enrolled at Texas public institution",
      "Demonstrate financial need",
    ],
    deadline: "Varies by institution",
    website: "https://www.highered.texas.gov/",
    essayRequired: false,
    renewable: true,
    national: false,
  },
  {
    id: "terry-foundation",
    name: "Terry Foundation Scholarship",
    type: "need-based",
    provider: "Terry Foundation",
    description:
      "Generous scholarship for Texas high school graduates attending one of 13 participating Texas universities. Covers full tuition, fees, books, and living expenses.",
    amount: 40000,
    eligibility: [
      "Texas resident and high school graduate",
      "Attend Terry-eligible Texas university",
      "Demonstrate financial need",
      "Strong academic record",
      "Leadership and community involvement",
    ],
    deadline: "January 15",
    website: "https://terryfoundation.org/",
    essayRequired: true,
    renewable: true,
    national: false,
  },
  {
    id: "national-merit",
    name: "National Merit Scholarship",
    type: "merit",
    provider: "National Merit Scholarship Corporation",
    description:
      "Prestigious merit-based scholarship for high-scoring PSAT/NMSQT students. Finalists compete for awards from corporate sponsors and universities.",
    amount: 2500,
    eligibility: [
      "U.S. high school student",
      "PSAT/NMSQT scores in top 1%",
      "Become a National Merit Finalist (semifinalist → finalist)",
    ],
    deadline: "October (PSAT administration)",
    website: "https://www.nationalmerit.org/",
    essayRequired: true,
    renewable: false,
    national: true,
  },
  {
    id: "coca-cola",
    name: "Coca-Cola Scholars Program",
    type: "merit",
    provider: "Coca-Cola Scholars Foundation",
    description:
      "Merit-based scholarship for high school seniors who demonstrate leadership, academic excellence, and community service.",
    amount: 20000,
    eligibility: [
      "U.S. high school senior",
      "Minimum 3.0 GPA",
      "Planning to attend accredited U.S. institution",
      "Demonstrated leadership and service",
    ],
    deadline: "October 31",
    website: "https://www.coca-colascholarsfoundation.org/",
    essayRequired: true,
    renewable: false,
    national: true,
  },
  {
    id: "gates-scholarship",
    name: "Gates Scholarship",
    type: "need-based",
    provider: "Bill & Melinda Gates Foundation",
    description:
      "Highly selective scholarship for outstanding minority high school seniors with significant financial need. Covers full cost of attendance.",
    amount: 80000,
    eligibility: [
      "U.S. citizen/eligible non-citizen",
      "African American, American Indian/Alaska Native, Asian Pacific Islander, or Hispanic American",
      "Pell-eligible",
      "Minimum 3.3 GPA",
    ],
    deadline: "September 15",
    website: "https://www.thegatesscholarship.org/",
    essayRequired: true,
    renewable: true,
    national: true,
  },
  {
    id: "hispanic-fund",
    name: "HSF Scholarship",
    type: "merit",
    provider: "Hispanic Scholarship Fund",
    description:
      "Scholarship for Hispanic American students with strong academic records planning to enroll in accredited U.S. institutions.",
    amount: 5000,
    eligibility: [
      "Hispanic heritage",
      "U.S. citizen or eligible non-citizen",
      "Minimum 3.0 GPA for high school / 2.5 for college",
      "Planning to enroll full-time in accredited U.S. institution",
    ],
    deadline: "February 15",
    website: "https://www.hsf.net/",
    essayRequired: true,
    renewable: false,
    national: true,
  },
  {
    id: "texas-gm",
    name: "Texas GM Scholarship",
    type: "merit",
    provider: "General Motors",
    description:
      "Scholarship for Texas students pursuing STEM degrees at Texas colleges. Focused on engineering, technology, and related fields.",
    amount: 10000,
    eligibility: [
      "Texas resident",
      "STEM major (engineering, CS, math, etc.)",
      "Minimum 3.0 GPA",
      "Attend Texas institution",
    ],
    deadline: "March 1",
    website: "https://www.gm.com/careers/students",
    essayRequired: true,
    renewable: true,
    national: false,
  },
  {
    id: "texas-opportunity",
    name: "Texas Opportunity Scholarship",
    type: "need-based",
    provider: "Texas Higher Education Coordinating Board",
    description:
      "Need-based scholarship for Texas students enrolled in participating Texas colleges. Priority to students from low-income families.",
    amount: 5000,
    eligibility: [
      "Texas resident",
      "Demonstrate financial need",
      "Enrolled at participating Texas institution",
    ],
    deadline: "Varies by institution",
    website: "https://www.highered.texas.gov/",
    essayRequired: false,
    renewable: true,
    national: false,
  },
  {
    id: "tamayo-scholarship",
    name: "Ruth B. TAMAYO Scholarship",
    type: "need-based",
    provider: "Texas Exes",
    description:
      "Scholarship for Texas students who have overcome adversity. Administered by the Texas Exes alumni association.",
    amount: 5000,
    eligibility: [
      "Texas resident",
      "Plan to attend UT Austin or UT system school",
      "Demonstrate financial need and overcoming adversity",
    ],
    deadline: "March 15",
    website: "https://www.texasexes.org/",
    essayRequired: true,
    renewable: false,
    national: false,
  },
  {
    id: "elks-mvs",
    name: "Elks National Foundation Most Valuable Student",
    type: "merit",
    provider: "Elks National Foundation",
    description:
      "National merit-based competition for high school seniors. Awards based on academics, leadership, and financial need.",
    amount: 50000,
    eligibility: [
      "U.S. high school senior",
      "U.S. citizen",
      "Strong academic and leadership record",
    ],
    deadline: "November 15",
    website: "https://www.elks.org/scholars/scholarships/mvs.cfm",
    essayRequired: true,
    renewable: false,
    national: true,
  },
];
